// Generated by CoffeeScript 2.2.0
var BoxSchema, Space, extend, set, untuple;

({extend, set, untuple} = require("./utils"));

Space = require("./space");

BoxSchema = function(box) {
  set(this, "_box", box);
  set(this, "_spaces", Object.create(null));
  return this;
};

extend(BoxSchema, {
  getSpace: function(name) {
    var space;
    if (!(space = this._spaces[name])) {
      this._spaces[name] = space = new Space(name, this._box);
    }
    return space;
  },
  renameSpace: function(old_name, new_name) {
    var space;
    if (space = this._spaces[old_name]) {
      this._spaces[new_name] = space;
      delete this._spaces[old_name];
    }
    return false;
  },
  deleteSpace: function(name) {
    return delete this._spaces[name];
  },
  load: async function() {
    var data, name, req, space, spaces;
    req = this._box._call("duran.spaces");
    req.retry = false;
    spaces = (await this._box._send(req).then(untuple));
    for (name in spaces) {
      data = spaces[name];
      if (!(space = this._spaces[name])) {
        this._spaces[name] = space = new Space(name, this._box);
      }
      space.id = data.id;
      space._format = data.format;
      space._fieldCount = data.field_count;
      space._indexMap = data.index_map;
    }
  }
});

module.exports = BoxSchema;
