// Generated by CoffeeScript 2.2.0
var AUTH, CALL, SELECT, badCommand, ip;

ip = require("../iproto");

AUTH = require("./auth");

CALL = require("./call");

SELECT = require("./select");

exports.get = function(cmd) {
  switch (cmd) {
    case ip.AUTH:
      return AUTH;
    case ip.CALL:
      return CALL;
    case ip.SELECT:
      return SELECT;
    default:
      throw badCommand(cmd);
  }
};

badCommand = function(cmd) {
  return Error("Unknown command: 0x" + (Buffer.from([cmd])).toString("hex"));
};
