// Generated by CoffeeScript 2.2.0
var Tuple, extend, set, unimpl;

({extend, set, unimpl} = require("../utils"));

Tuple = function(space) {
  this.space = space;
  set(this, "_trace", Error());
  return this;
};

extend(Tuple, {
  update: unimpl("Tuple#update"),
  replace: unimpl("Tuple#replace"),
  delete: unimpl("Tuple#delete")
});

module.exports = Tuple;
